### ISSUE TITLE
I can't initialize NSDictionary or NSMutableDictionary in lua

### ISSUE THREAD

**Issue by softwind0214** [probablycorey/wax#57]
I'm writing a method in lua, which should return a dictionary. Firstly, I try to use NSDictionray:dictionaryWithObjectsAndKeys(), but it didn't work. Later, I try NSMutableDictionary:init() or NSDictionary:init():mutableCopy(), but it crashed here:

```
    if (returnedInstanceUserdata) { // Could return nil
        [returnedInstanceUserdata->instance release]; // Wax automatically retains a copy of the object, so the alloc needs to be released
    }
```

Is there any way to create and return a dictionary in lua?

**Comment by intheway** [comment]
you should just use lua table. like `local dict = {k1="v1", k2="v2"}`
