### ISSUE TITLE
How do I compile wax_stdlib about 64bit

### ISSUE THREAD

**Issue by linmingzhi** [probablycorey/wax#59]
My project is developmenting for more half a year in wax_hua,bug apple must support 64bit on 2015.02.01. but My project Does not support arm64 now. Now what should I do。and How do I compile wax_stdlib about 64bit。

**Comment by KimReboot** [comment]
+1

**Comment by felipejfc** [comment]
+1

**Comment by maxfong** [comment]
+10086

**Comment by felipejfc** [comment]
I figured out how to compile wax_stdlib with 64bits support, take a look guys
https://github.com/felipejfc/wax_x86-64

However there is still work to do, the library is being successfully loaded but it is not working as expected yet, the method pcallUserdata on it's 5th call is making reference to a invalid address in memory and I can't figure out why yet. I invite you all to try to fix this. Later today I'll update the readme on my fork with the instructions of how I've compiled for 64 bit but you can start debugging with the precompiled one to find why it is not working and fell free to push fixes. remember to compile the projects in ARM64.

Regards

**Comment by maxfong** [comment]
i try compiled wax_stdlib.h  64-bit 
https://github.com/maxfong/wax_stdlib_x64

**Comment by felipejfc** [comment]
does this work?

**Comment by felipejfc** [comment]
Friends, I've got it fully working on both architectures, here you go:

https://github.com/felipejfc/wax_x86-64

Regards!

**Comment by maxfong** [comment]
int size = wax_fromObjc(L, type, usedArgs); -> int size = wax_sizeOfTypeDescription(type); fix crash...

**Comment by linmingzhi** [comment]
download  wax_x86-64  ，in States (without wax.framework),  try on iphone5 (hardware support 32bit)，it run ok. but  on iphone6plue (hardware support 32bit and 64bit)，it crash ，in wax_helpers.m ,  "if ([instance isKindOfClass:[NSString class]]) {"  thread 1:EXC_BAD_ACCESS(code=1,address=0x81a59408e1b9)

**Comment by felipejfc** [comment]
strange, I can run well here on iphone 6 simulator!

**Comment by linmingzhi** [comment]
iphone 6 simulator run OK,but iphone 6 machine run crash 。 With the above question。

**Comment by maxfong** [comment]
@felipejfc Thanks，my wax_stdlib_x64 Only how create wax_stdlib_x64.h file;
my WaxPatch_X64 using your's wax_x86-64 find iphone6 crash, if change int size = wax_fromObjc(L, type, usedArgs); to int size = wax_sizeOfTypeDescription(type); ，Some features are not available。。。

**Comment by felipejfc** [comment]
If you change this line you'll miss some features @maxfong, I'm aware of the bug now @linmingzhi, I'm getting crash now using a device too... I'll try to figure it out! THe problem lies in grabbing va_list

**Comment by felipejfc** [comment]
I've put a description on the problem in my repo

https://github.com/felipejfc/wax_x86-64

**Comment by maxfong** [comment]
HI,@felipejfc, i test your's code,find OC delegate run crash and wax examples run crash，thank you for your efforts ：>，come on

**Comment by felipejfc** [comment]
@maxfong I'm aware of the issues, I'm currently working on a fix, I can already access the arguments but I need to fix an issue with pointers... I'm very near of fixing it, keep an eye on it

**Comment by felipejfc** [comment]
@linmingzhi @maxfong it must be fully working now, can you guys confirm?

regards!

**Comment by felipejfc** [comment]
Oh well I guess I identified another issue with multiple arguments method calls that is not covered by the tests --''
I'll be fixing it later

**Comment by felipejfc** [comment]
Ok, now I think it is really working @linmingzhi @maxfong @KimReboot @HuJianChong https://github.com/felipejfc/wax_x86-64

I managed to run tests and examples

**Comment by maxfong** [comment]
@felipejfc ,if i  // for (int i = 0; i < n-2; i++) { free(sharedMemoryForArgs[i]); },it will work OK,THX

**Comment by felipejfc** [comment]
If you free then it don't work? I think it's better to free them to avoid a memory leak...

**Comment by maxfong** [comment]
@felipejfc my repo:https://github.com/maxfong/WaxPatch_X64/tree/develop, run develop branch, for free sharedMemoryForArgs will crash

**Comment by felipejfc** [comment]
@maxfong it is true that it was causing a crash, I released a new commit with fix for that, the arguments needs to be freed so that no memory leak occurs.

**Comment by linmingzhi** [comment]
NSMutableString *pp = [[NSMutableString alloc] init];
                 NSString *dir = [[[NSBundle mainBundle] bundlePath] stringByAppendingPathComponent:modeName];
                NSArray *fileList = [fileManager contentsOfDirectoryAtPath:dir error:&error];
                for (NSString *file in fileList) {
                    //load A lot of resources (.lua) in the  file
                    [pp appendFormat:@"%@/?.lua;",[dir stringByAppendingPathComponent:file]];
                }
                [pp appendFormat:@"%@/?/%@",dir,[[dir stringByAppendingPathComponent:[dic objectForKey:@""]] stringByAppendingPathComponent:[dic objectForKey:@"Enter"]]];
                setenv(LUA_PATH, [pp UTF8String], 1);
                wax_start((char *)[[dic objectForKey:@"Enter"]  UTF8String], nil);


then causing a crash ../stdlib/waxClass.lua:28: Can't override method with return type d .And @maxfong is a bit similar ---run develop branch, for free sharedMemoryForArgs will crash

**Comment by felipejfc** [comment]
@linmingzhi can you provide more information on this crash? what are you trying to do? are you using my last repo version? I've already solved the problem @maxfong pointed for sharedMemoryForArgs

**Comment by maxfong** [comment]
HI @linmingzhi  , @felipejfc did 
//    for (int i = 0; i < n-2; i++) {
//        free(sharedMemoryForArgs[i]);
//    }
//    
//    free(sharedMemoryForArgs);

**Comment by felipejfc** [comment]
@maxfong @linmingzhi https://github.com/felipejfc/wax_x86-64/commit/45bbb5e757295b31ba3e275f8e3404d35c0b30a1

To avoid memory leak!

**Comment by IPv6** [comment]
trying to use https://github.com/felipejfc/n-wax to replace wax with 64bit-enabled one.
but i cant compile my app (
1) build using "master branch" fails with linker error
```
Undefined symbols for architecture arm64:
  "_ffi_type_pointer", referenced from:
      _overrideMethod in wax_instance.o
  "_ffi_typeForTypeEncoding", referenced from:
      _overrideMethod in wax_instance.o
  "_createFFIClosure", referenced from:
      _overrideMethod in wax_instance.o
ld: symbol(s) not found for architecture arm64
```

2) build with "no-ffi" branch fails with linker errors
```
Undefined symbols for architecture armv7:
  "_NewArgumentList", referenced from:
      _myForwardInvocation in wax_instance.o
  "_addArgument", referenced from:
      _myForwardInvocation in wax_instance.o
  "_freeArguments", referenced from:
      _myForwardInvocation in wax_instance.o
ld: symbol(s) not found for architecture armv7
```
in both cases i cant find this method anywhere (except bold declarations)
@felipejfc any advice? thanks for trying to keep this project up! wax is convinient indeed, it`s a pity it is dropped by probablycore //

**Comment by felipejfc** [comment]
@IPv6 I think  you are not including all n-wax files in your project, check if you are including wax_ffi_closure .m and .h and also /lib/libffi files

**Comment by felipejfc** [comment]
About the no_ffi branch you are probably not including wax_arguments .m and .h. In both cases you need to add files to your project, with the hacks i made for making it work i added new files into Wax. Note that I do not know which version is more performatic /stable. With or without libffi. Ild  like your feedback

**Comment by caikelun** [comment]
@felipejfc Hi, I have just tested n-wax(the newest master branch: 89f3d35cf61227a834f15242b061cd32aa4b919d), the "states example" crash on iphone6 plus hardware device(Thread1: EXC_BAD_ACCESS (code=2, address=0x104aa8490)), but run OK on iphone6 plus simulator. Bug from libffi??

**Comment by qazaaa** [comment]
@felipejfc Hi,would you please show me some details about how to compile wax_stdlib_64.h，thanks

**Comment by maxfong** [comment]
@qazaaa https://github.com/maxfong/wax_stdlib_x64

**Comment by intheway** [comment]
wax is maintained by alibaba now, 64bit is support. see https://github.com/alibaba/wax
