### ISSUE TITLE
How to using Objective-C Block

### ISSUE THREAD

**Issue by maxfong** [probablycorey/wax#60]
wax does not support block

**Comment by maxfong** [comment]
@felipejfc @linmingzhi

**Comment by felipejfc** [comment]
example code?

**Comment by todicus** [comment]
This is a bit of a hack on top of Wax, but I can verify that it does work: https://groups.google.com/d/msg/iphonewax/mMhRCRwfEjQ/dPlA3wveeqoJ

**Comment by felipejfc** [comment]
this is a good hack, I think this can be done without the coersion and for N arguments, will take a look on that later...

**Comment by maxfong** [comment]
@todicus , thx，it‘s work

**Comment by void-main** [comment]
@todicus Is it working? I got EXC_BAD_ACCESS..

**Comment by felipejfc** [comment]
@void-main I tested it and it worked. I tested with my fork

**Comment by intheway** [comment]
wax is maintained by alibaba, block is support. see https://github.com/alibaba/wax
