### ISSUE TITLE
write Masonry in lua

### ISSUE THREAD

**Issue by xxfenxx** [probablycorey/wax#63]
When I try to write a UIButton and layout with Masonry it does not work! Who can look up in my code, it happen to crash while running！

Here:

add a UIImageView to cell.contentView

  --local weakSelf = self
  button:masUNDERxLINEmakeConstraints(
            toblock(

```
           function(make)
              make:left():masUNDERxLINEequalTo(self:contentView())
              make:top():masUNDERxLINEequalTo(self:contentView())
              make:right():masUNDERxLINEequalTo(self:contentView())
              make:height():masUNDERxLINEequalTo(50)

             end,{"void","id"}
          )
     )
```

**Comment by probablycorey** [comment]
You might get a better answer in https://github.com/alibaba/wax, they are now maintaining wax.
